### ISSUE TITLE
MariaDB failure querying mysql schema

### ISSUE THREAD

**Issue by heiho1** [adriens/schemacrawler-plugin-neo4j#9]
Hi,

I am testing your plugin against the latest SchemaCrawler release download.  Your plugin builds fine from the git checkout and I drop the jar into the _schemacrawler plugin directory but the "neo4j" command fails after retrieving database metadata:

"""
Apr 22, 2016 1:08:16 PM us.fatehi.commandlineparser.CommandLineUtility logSafeArguments
INFO: Command line:
-host=01-mysql-my.net
-database=mysql
-user=root
-password=*****
-schemas=api*
-c=neo4j
-infolevel=maximum
-server=mysql
-hideemptytables
-loglevel=CONFIG
-outputDir=~/neo4jdata
-sequences=.*
Apr 22, 2016 1:08:16 PM us.fatehi.commandlineparser.CommandLineUtility logFullStackTrace
SEVERE: Cannot perform operation: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'neo4j' at line 1
Query is : neo4j
schemacrawler.schemacrawler.SchemaCrawlerException: Cannot perform operation: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'neo4j' at line 1
Query is : neo4j
    at schemacrawler.tools.text.operation.OperationExecutable.executeOn(OperationExecutable.java:126)
    at schemacrawler.tools.executable.SchemaCrawlerExecutable.executeOn(SchemaCrawlerExecutable.java:118)
    at schemacrawler.tools.executable.BaseStagedExecutable.execute(BaseStagedExecutable.java:94)
    at schemacrawler.tools.commandline.SchemaCrawlerCommandLine.execute(SchemaCrawlerCommandLine.java:133)
    at schemacrawler.Main.main(Main.java:88)
Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'neo4j' at line 1
Query is : neo4j
    at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:125)
    at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69)
    at org.mariadb.jdbc.MariaDbStatement.executeQueryEpilog(MariaDbStatement.java:250)
    at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:278)
    at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStatement.java:291)
    at sf.util.DatabaseUtility.executeSql(DatabaseUtility.java:145)
    at schemacrawler.tools.text.operation.OperationExecutable.executeOn(OperationExecutable.java:115)
    ... 4 more
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'neo4j' at line 1
Query is : neo4j
    at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:908)
    at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:574)
    at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:269)
    ... 7 more

jrichards1:~ jrichards1$
"""

Is "neo4j" the right command?

Thanks,

James

**Comment by heiho1** [comment]
Please disregard.  This was my error.

**Comment by adriens** [comment]
Hi, i'm upgrading to latestschemacrawler version and latest neo4j version.
Did you manage to get a nice looking graph of your db ?

**Comment by heiho1** [comment]
Hi, 

I was able to get a graph output.  I did make some tweaks to the AdditonalExecutable.  In my case, some name calls like "schema.getName()" were returning null pointer exception.  I've made a Gist of my changes:

https://gist.github.com/heiho1/75eb15c5190d2492974b5a946408a105

**Comment by adriens** [comment]
Could you please make me a PR so i can review your changes easier ?
